"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def construct_fibonacci(limitation):
    fibonacci = []
    first = 0
    second = 1

    while True:
        # fibonacci
        previous = second
        second = first + second

        # break the cycle
        if second > limitation:
            break

        # add fibonacci number to sequence
        fibonacci.append(second)

        # update the elements
        first = previous

    return fibonacci


def sum_of_the_even_value(fibonacci: list):
    sum = 0

    for i in fibonacci:
        if i % 2 == 0:
            sum += i

    return sum


if __name__ == "__main__":
    fib = construct_fibonacci(4000000)
    my_sum = sum_of_the_even_value(fib)
    print(my_sum)
